---
baseURL: https://harishnarayanan.org/
disableHugoGeneratorInject: true
languageCode: en-gb
layoutDir: layout
metaDataFormat: yml
pluralizeListTitles: false
staticDir: assets
taxonomies: false
title: Harish Narayanan
...
