---
- name: Install nginx
  become: yes
  apt:
    name=nginx
    state=latest
    update_cache=yes

- name: Setup the default configuration for nginx
  become: yes
  copy:
    src=nginx.conf
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Delete the default website enabled by nginx
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Create a folder to house the website content
  file:
    path: "{{ content_dir }}/{{ domain_name }}"
    state: directory

- name: Setup this website as one of the available nginx sites
  become: yes
  template:
    src=site.j2
    dest=/etc/nginx/sites-available/{{ domain_name }}
  notify: restart nginx

- name: Setup this website as one of the enabled nginx sites
  become: yes
  file:
    src=/etc/nginx/sites-available/{{ domain_name }}
    dest=/etc/nginx/sites-enabled/{{ domain_name }}
    state=link
  notify: restart nginx

- name: Configure firewall rules to allow HTTP(S)
  become: yes
  ufw:
    rule={{ item.rule }}
    port={{ item.port }}
    proto={{ item.proto }}
  with_items:
    - { rule: 'allow', port: '80', proto: 'tcp' }
    - { rule: 'allow', port: '443', proto: 'tcp' }

- name: Enable the nginx service
  become: yes
  service:
    name=nginx
    enabled=yes