---
- name: Create swap file
  become: yes
  command: fallocate -l {{ 2*ansible_memtotal_mb }}M /swapfile
           creates=/swapfile

- name: Change swap file permissions
  become: yes
  file: path=/swapfile
        mode=0600

- name: Check swap file type
  become: yes
  command: file /swapfile
  register: swapfile
  changed_when: False

- name: Start using swap file
  become: yes
  command: mkswap /swapfile
  when: swapfile.stdout.find('swap file') == -1

- name: Commit swap file to fstab
  become: yes
  mount:
    name=none
    src=/swapfile
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present

- name: Mount swap
  become: yes
  command: swapon /swapfile
  when: ansible_swaptotal_mb < 1

- name: Install common base packages
  become: yes
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - fail2ban
    - emacs25-nox
    - htop
    - tree
    - git
    - screen
    - ufw

- name: Configure default firewall rules
  become: yes
  ufw:
    direction={{ item.direction }}
    policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Configure base firewall rule to allow SSH
  become: yes
  ufw:
    rule: limit
    name: OpenSSH

- name: Enable firewall logging
  become: yes
  ufw: logging=on
  notify:
    - restart firewall

- name: Enable firewall
  become: yes
  ufw: state=enabled

- name: Configure git
  become: yes
  become_user: "{{ remote_user_name }}"
  template:
    src=.gitconfig.j2
    dest=~/.gitconfig
